### ISSUE TITLE
커밋 메시지 룰과 깃 전략을 정하면 어떨까요?

### ISSUE THREAD

**Issue by youngrongoh** [Meme-dulecy/frontend#1]
## 커밋 메시지 룰

작업 내용을 커밋 메시지만 봐도 대략 알 수 있게 메시지 룰을 정하면 어떨까요?

### 예시
1. 타입: [범위] 내용
    - feat: [메인화면] 시간에 따라 밈 이동
    - fix: [로그인] 구글 인증 페이지가 새 창에서 열리도록 수정
    - chore. [스크립트] 배포 스크립트 작성
3. 타입: 내용
    - feat: 메인화면에서 시간에 따라 밈 이동
    - fix: 구글 인증 페이지가 새 창에서 열리도록 수정
    - chore. 배포 스크립트 작성

#### 참고
[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)
![summary](https://github.com/Meme-dulecy/frontend/assets/64844815/206cb841-5621-4ab0-a487-b5195b55ce39)

## 깃 전략

각자 작업할 브랜치를 만들고 진행을 하면 좋을 것 같아요. main 브랜치를 로컬에 받아서 작업하고 푸시하려고 하면 작업 내용 추적과 코드 충돌 해결이 어려워 질 것 같아요. 브랜치 이름 규칙과 깃 전략을 정하면 어떨까요?

#### 참고
[[Git] git-flow 소개, 설치 및 사용법](https://hbase.tistory.com/60)

**Comment by khkh0109** [comment]
좋습니다!

**Comment by SangWoo9734** [comment]
좋습니다!

커밋 메세지는 `타입: 내용`으로 많이 사용했었고,
브랜치 이름이랑 깃 전략은 그때그때 팀원들과 맞춰서 사용했습니다!

제안해주시면 따라가겠습니다!

**Comment by khkh0109** [comment]
저도 커밋 메세지는 `타입: 내용`으로 많이 사용했습니다! 
`타입: [범위] 내용` 이렇게 작성하면 더 명확하게 알 수 있어서 좋아보이네요!

**Comment by khkh0109** [comment]
브랜치는 기능명으로 정하기로 조조와 상의했습니다! 
예시: 밈 상세페이지 -> feat/meme-detail

**Comment by youngrongoh** [comment]
이것은 첫 스프린트 때 정해서 이미 규칙을 지키고 있기 때문에 클로즈하겠습니다.
