### ISSUE TITLE
새로고침 했을 때 항상 메인화면이 표시될텐데..

### ISSUE THREAD

**Issue by youngrongoh** [Meme-dulecy/frontend#2]
#### 필요성
화면이  몇개 없긴 하지만 새로고침 할 때마다 메인화면이 나올거에요. react-router를 이용해 UI와 라우트 주소를 연결해주면 새로고침 했을 때도 사용하던 모달이나 페이지를 유지시켜줄 수 있어요!

#### 중요도
지금 생각했을 때 반드시 필요한 기능까진 아닐 것 같긴합니다.

**Comment by SangWoo9734** [comment]
저도 말씀해주신것 처럼 반드시 필요한 건 아닐 것 같은데 있으면 사용자가 편할 것 같긴 합니다!

**Comment by youngrongoh** [comment]
이건 이미 구현된 것 같네요. 클로즈하겠습니다!
https://github.com/Meme-dulecy/frontend/blob/e57d801d1a21d874bb91a3dd955ea93c54d55326/src/router/index.tsx#L14-L18
